In [83]:
import os  
import pandas as pd 
import numpy as np 
import csv 
print (os.getcwd())


C:\Users\saikat


In [71]:
excel=pd.read_excel(r'C:\Users\saikat\Desktop\results_9.xlsx')
results=excel.to_numpy()

In [72]:
results

array([['{', nan, nan, ..., nan, nan, nan],
       [nan, 'frame_id:1', nan, ..., nan, nan, nan],
       [nan,
        'filename:"C:\\Users\\saikat\\Desktop\\darknet_opencv\\data\\images\\1.jpg"',
        nan, ..., nan, nan, nan],
       ...,
       [nan, ']', nan, ..., nan, nan, nan],
       ['}', nan, nan, ..., nan, nan, nan],
       [']', nan, nan, ..., nan, nan, nan]], dtype=object)

In [73]:
#the following are the class ids of the vehicles normally seen on the roads
#car:2,motorbike :3,bus:5,truck:7
count_dict={}
#dictionary to count the number of vehicles 
num_frames=0
for  i  in  range (results.shape[0]):
    
    if (results[i,1]=='objects:'):
        num_frames=num_frames+1
        string =results[i-2,1]
        frame_id =int (string[len(string)-1])
        j=i+1
        count_veh=0
        while (results[j,1]!=']' ):
            str=results[j,1]
            class_id = int (str[len(str)-1])
            #print(class_id)
            if (class_id ==2 or class_id==3 or class_id==5 or class_id ==7):
                count_veh=count_veh+1
            j=j+1
        count_dict[frame_id]=count_veh 
            
    

In [74]:
count_dict

{1: 13, 2: 24, 3: 27, 4: 20, 5: 46, 6: 45, 7: 22, 8: 29, 9: 14}

In [80]:
#let the threshold of conjestion be >=46
#frame id corresponding to grid 
#frame_id   grid 
#1 00
#2 01
#3 02
#4 10
#5 11
#6 12
#7 20
#8 21
#9 22
red_light_duration=np.ones((3,3))
red_light_duration=red_light_duration *2

#print (red_light_duration )
#taking the threshold of congestion to be 46
thres=46
c=1
for i in range (3):
    for  j in range (3):
            traffic=count_dict[c]
            c=c+1
            if (traffic>=thres):
                x=i
                y=j
                break
    
print(x,y)   
red_light_duration [x,y+1]=4
red_light_duration [x,y-1]=4
red_light_duration [x+1,y]=4
red_light_duration [x-1,y]=4
main_dict={}
c=1
for  i in range (3):
    for j in range (3):
        
        main_dict[c]=red_light_duration [i,j]
        c=c+1


[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]
1 1


In [81]:
#this is the modified red light duration of every junction 
red_light_duration 

array([[2., 4., 2.],
       [4., 2., 4.],
       [2., 4., 2.]])

In [82]:
main_dict

{1: 2.0, 2: 4.0, 3: 2.0, 4: 4.0, 5: 2.0, 6: 4.0, 7: 2.0, 8: 4.0, 9: 2.0}

In [88]:
#dump into a csv file 
w = csv.writer(open("output.csv", "w"))
for key, val in main_dict.items():
    print (key,val)
    w.writerow([key, val])

1 2.0
2 4.0
3 2.0
4 4.0
5 2.0
6 4.0
7 2.0
8 4.0
9 2.0
